### ISSUE TITLE
Tests Freeze Permanently on Sort, Min, Max

### ISSUE THREAD

**Issue by ghost** [ROCmSoftwarePlatform/cutorch_hip#13]
Conveniently the last three runs I did ended up freezing on different test cases, so I'll just paste:

```
cathal@thinkum:~/torch$ th -lcutorch -e "cutorch.test()"
seed: 	1496310658	
Running 163 tests
  1/163 expand .......................................................... [PASS]
  2/163 trunc2 .......................................................... [PASS]
  3/163 cmin ............................................................ [PASS]
  4/163 sign1 ........................................................... [PASS]
  5/163 bernoulli ....................................................... [FAIL]
  6/163 addmv ........................................................... [PASS]
  7/163 trace ........................................................... [PASS]
  8/163 largeNoncontiguous .............................................. [PASS]
  9/163 sort ............................................................ [WAIT]^C^C
cathal@thinkum:~/torch$ th -lcutorch -e "cutorch.test()"
seed: 	1496310662	
Running 163 tests
  1/163 cross ........................................................... [PASS]
  2/163 storageToTable .................................................. [PASS]
  3/163 exp2 ............................................................ [PASS]
  4/163 abs2 ............................................................ [PASS]
  5/163 norm ............................................................ [PASS]
  6/163 multinomial_vector .............................................. [PASS]
  7/163 logicalValue .................................................... [PASS]
  8/163 gather .......................................................... [PASS]
  9/163 cmax ............................................................ [PASS]
 10/163 frac1 ........................................................... [PASS]
 11/163 cosh1 ........................................................... [PASS]
 12/163 get_device ...................................................... [PASS]
 13/163 sigmoid2 ........................................................ [PASS]
 14/163 addbmm .......................................................... [PASS]
 15/163 clamp1 .......................................................... [PASS]
 16/163 cinv1 ........................................................... [PASS]
 17/163 allAndAny ....................................................... [PASS]
 18/163 floor1 .......................................................... [PASS]
 19/163 baddbmmTransposed ............................................... [PASS]
 20/163 mv .............................................................. [PASS]
 21/163 asin1 ........................................................... [PASS]
 22/163 viewAs .......................................................... [PASS]
 23/163 reshape ......................................................... [PASS]
 24/163 add ............................................................. [PASS]
 25/163 tensorToTable ................................................... [PASS]
 26/163 multi_gpu_copy_noncontig ........................................ [PASS]
 27/163 cat ............................................................. [PASS]
 28/163 permute ......................................................... [PASS]
 29/163 expand .......................................................... [PASS]
 30/163 addmm ........................................................... [PASS]
 31/163 sqrt2 ........................................................... [PASS]
 32/163 split ........................................................... [PASS]
 33/163 elementSize ..................................................... [PASS]
 34/163 random_seed ..................................................... [PASS]
 35/163 pow2 ............................................................ [PASS]
 36/163 logNormal ....................................................... [FAIL]
 37/163 sqrt1 ........................................................... [PASS]
 38/163 cos2 ............................................................ [PASS]
 39/163 sin2 ............................................................ [PASS]
 40/163 logicalTensor ................................................... [PASS]
 41/163 largeNoncontiguous .............................................. [PASS]
 42/163 cauchy .......................................................... [PASS]
 43/163 maskedCopy ...................................................... [PASS]
 44/163 scatterFill ..................................................... [PASS]
 45/163 fill ............................................................ [PASS]
 46/163 atan2 ........................................................... [PASS]
 47/163 squeeze ......................................................... [PASS]
 48/163 rsqrt ........................................................... [PASS]
 49/163 addr ............................................................ [PASS]
 50/163 mean ............................................................ [PASS]
 51/163 min ............................................................. [WAIT]^C^C
cathal@thinkum:~/torch$ th -lcutorch -e "cutorch.test()"
seed: 	1496310676	
Running 163 tests
  1/163 cosh1 ........................................................... [PASS]
  2/163 log1 ............................................................ [PASS]
  3/163 clamp3 .......................................................... [PASS]
  4/163 sigmoid1 ........................................................ [PASS]
  5/163 repeatTensor .................................................... [PASS]
  6/163 pow1 ............................................................ [PASS]
  7/163 addr ............................................................ [PASS]
  8/163 cmin ............................................................ [PASS]
  9/163 copyRandomizedTest .............................................. [PASS]
 10/163 scatter ......................................................... [PASS]
 11/163 indexSelect2 .................................................... [PASS]
 12/163 tanh1 ........................................................... [PASS]
 13/163 mv .............................................................. [PASS]
 14/163 mean ............................................................ [PASS]
 15/163 maskedSelect .................................................... [PASS]
 16/163 cumsum .......................................................... [PASS]
 17/163 exponential ..................................................... [PASS]
 18/163 reshape ......................................................... [PASS]
 19/163 var ............................................................. [PASS]
 20/163 multinomial_without_replacement ................................. [FAIL]
 21/163 cat ............................................................. [PASS]
 22/163 asin2 ........................................................... [PASS]
 23/163 indexCopy ....................................................... [PASS]
 24/163 indexAdd2 ....................................................... [PASS]
 25/163 chunk ........................................................... [PASS]
 26/163 ceil1 ........................................................... [PASS]
 27/163 isSameSizeAs .................................................... [PASS]
 28/163 sin2 ............................................................ [PASS]
 29/163 cudaEvent ....................................................... [PASS]
 30/163 renorm .......................................................... [PASS]
 31/163 cudaStorageTypeCopy ............................................. [PASS]
 32/163 pow2 ............................................................ [PASS]
 33/163 round2 .......................................................... [PASS]
 34/163 csub ............................................................ [PASS]
 35/163 logicalValue .................................................... [PASS]
 36/163 clamp2 .......................................................... [PASS]
 37/163 cumprod ......................................................... [PASS]
 38/163 powExponentTensor ............................................... [PASS]
 39/163 multinomial_without_replacement_gets_all ........................ [FAIL]
 40/163 cos2 ............................................................ [PASS]
 41/163 normal .......................................................... [PASS]
 42/163 restore_rng ..................................................... [FAIL]
 43/163 fill ............................................................ [PASS]
 44/163 floor1 .......................................................... [PASS]
 45/163 logNormal ....................................................... [PASS]
 46/163 exp2 ............................................................ [PASS]
 47/163 sign2 ........................................................... [PASS]
 48/163 cudaTypeCopy .................................................... [PASS]
 49/163 streamWaitFor ................................................... [PASS]
 50/163 max ............................................................. [WAIT]^C^C
```

Built on Lua 5.2, mostly according to instructions! I initially had built for LuaJit but hit the same bug, so I went back to 5.2.

On that note; it would help if the ROCm install docs for this were more clear; why Lua5.2 instead of LuaJIT? It just says that ye found it helpful, but not why. LuaJIT has a lot of advantages over 5.2, so it's a pity to miss out on those.

**Comment by gstoner** [comment]
CUtorch is still in development
On Jun 1, 2017, at 10:53 AM, Cathal Garvey <notifications@github.com<mailto:notifications@github.com>> wrote:


Conveniently the last three runs I did ended up freezing on different test cases, so I'll just paste:

cathal@thinkum:~/torch$ th -lcutorch -e "cutorch.test()"
seed:   1496310658
Running 163 tests
  1/163 expand .......................................................... [PASS]
  2/163 trunc2 .......................................................... [PASS]
  3/163 cmin ............................................................ [PASS]
  4/163 sign1 ........................................................... [PASS]
  5/163 bernoulli ....................................................... [FAIL]
  6/163 addmv ........................................................... [PASS]
  7/163 trace ........................................................... [PASS]
  8/163 largeNoncontiguous .............................................. [PASS]
  9/163 sort ............................................................ [WAIT]^C^C
cathal@thinkum:~/torch$ th -lcutorch -e "cutorch.test()"
seed:   1496310662
Running 163 tests
  1/163 cross ........................................................... [PASS]
  2/163 storageToTable .................................................. [PASS]
  3/163 exp2 ............................................................ [PASS]
  4/163 abs2 ............................................................ [PASS]
  5/163 norm ............................................................ [PASS]
  6/163 multinomial_vector .............................................. [PASS]
  7/163 logicalValue .................................................... [PASS]
  8/163 gather .......................................................... [PASS]
  9/163 cmax ............................................................ [PASS]
 10/163 frac1 ........................................................... [PASS]
 11/163 cosh1 ........................................................... [PASS]
 12/163 get_device ...................................................... [PASS]
 13/163 sigmoid2 ........................................................ [PASS]
 14/163 addbmm .......................................................... [PASS]
 15/163 clamp1 .......................................................... [PASS]
 16/163 cinv1 ........................................................... [PASS]
 17/163 allAndAny ....................................................... [PASS]
 18/163 floor1 .......................................................... [PASS]
 19/163 baddbmmTransposed ............................................... [PASS]
 20/163 mv .............................................................. [PASS]
 21/163 asin1 ........................................................... [PASS]
 22/163 viewAs .......................................................... [PASS]
 23/163 reshape ......................................................... [PASS]
 24/163 add ............................................................. [PASS]
 25/163 tensorToTable ................................................... [PASS]
 26/163 multi_gpu_copy_noncontig ........................................ [PASS]
 27/163 cat ............................................................. [PASS]
 28/163 permute ......................................................... [PASS]
 29/163 expand .......................................................... [PASS]
 30/163 addmm ........................................................... [PASS]
 31/163 sqrt2 ........................................................... [PASS]
 32/163 split ........................................................... [PASS]
 33/163 elementSize ..................................................... [PASS]
 34/163 random_seed ..................................................... [PASS]
 35/163 pow2 ............................................................ [PASS]
 36/163 logNormal ....................................................... [FAIL]
 37/163 sqrt1 ........................................................... [PASS]
 38/163 cos2 ............................................................ [PASS]
 39/163 sin2 ............................................................ [PASS]
 40/163 logicalTensor ................................................... [PASS]
 41/163 largeNoncontiguous .............................................. [PASS]
 42/163 cauchy .......................................................... [PASS]
 43/163 maskedCopy ...................................................... [PASS]
 44/163 scatterFill ..................................................... [PASS]
 45/163 fill ............................................................ [PASS]
 46/163 atan2 ........................................................... [PASS]
 47/163 squeeze ......................................................... [PASS]
 48/163 rsqrt ........................................................... [PASS]
 49/163 addr ............................................................ [PASS]
 50/163 mean ............................................................ [PASS]
 51/163 min ............................................................. [WAIT]^C^C
cathal@thinkum:~/torch$ th -lcutorch -e "cutorch.test()"
seed:   1496310676
Running 163 tests
  1/163 cosh1 ........................................................... [PASS]
  2/163 log1 ............................................................ [PASS]
  3/163 clamp3 .......................................................... [PASS]
  4/163 sigmoid1 ........................................................ [PASS]
  5/163 repeatTensor .................................................... [PASS]
  6/163 pow1 ............................................................ [PASS]
  7/163 addr ............................................................ [PASS]
  8/163 cmin ............................................................ [PASS]
  9/163 copyRandomizedTest .............................................. [PASS]
 10/163 scatter ......................................................... [PASS]
 11/163 indexSelect2 .................................................... [PASS]
 12/163 tanh1 ........................................................... [PASS]
 13/163 mv .............................................................. [PASS]
 14/163 mean ............................................................ [PASS]
 15/163 maskedSelect .................................................... [PASS]
 16/163 cumsum .......................................................... [PASS]
 17/163 exponential ..................................................... [PASS]
 18/163 reshape ......................................................... [PASS]
 19/163 var ............................................................. [PASS]
 20/163 multinomial_without_replacement ................................. [FAIL]
 21/163 cat ............................................................. [PASS]
 22/163 asin2 ........................................................... [PASS]
 23/163 indexCopy ....................................................... [PASS]
 24/163 indexAdd2 ....................................................... [PASS]
 25/163 chunk ........................................................... [PASS]
 26/163 ceil1 ........................................................... [PASS]
 27/163 isSameSizeAs .................................................... [PASS]
 28/163 sin2 ............................................................ [PASS]
 29/163 cudaEvent ....................................................... [PASS]
 30/163 renorm .......................................................... [PASS]
 31/163 cudaStorageTypeCopy ............................................. [PASS]
 32/163 pow2 ............................................................ [PASS]
 33/163 round2 .......................................................... [PASS]
 34/163 csub ............................................................ [PASS]
 35/163 logicalValue .................................................... [PASS]
 36/163 clamp2 .......................................................... [PASS]
 37/163 cumprod ......................................................... [PASS]
 38/163 powExponentTensor ............................................... [PASS]
 39/163 multinomial_without_replacement_gets_all ........................ [FAIL]
 40/163 cos2 ............................................................ [PASS]
 41/163 normal .......................................................... [PASS]
 42/163 restore_rng ..................................................... [FAIL]
 43/163 fill ............................................................ [PASS]
 44/163 floor1 .......................................................... [PASS]
 45/163 logNormal ....................................................... [PASS]
 46/163 exp2 ............................................................ [PASS]
 47/163 sign2 ........................................................... [PASS]
 48/163 cudaTypeCopy .................................................... [PASS]
 49/163 streamWaitFor ................................................... [PASS]
 50/163 max ............................................................. [WAIT]^C^C


Built on Lua 5.2, mostly according to instructions! I initially had built for LuaJit but hit the same bug, so I went back to 5.2.

On that note; it would help if the ROCm install docs for this were more clear; why Lua5.2 instead of LuaJIT? It just says that ye found it helpful, but not why. LuaJIT has a lot of advantages over 5.2, so it's a pity to miss out on those.

**Comment by ghost** [comment]
Ah, apologies; the build docs suggested that "most tests pass", which I took to mean that the test suite should finish, with some errors.

**Comment by bensander** [comment]
We added a runtests.sh script that runs each test as a separate process.  So you will get full results even running even if one test fails.

On Jun 2, 2017, at 4:19 AM, Cathal Garvey <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah, apologies; the build docs suggested that "most tests pass", which I took to mean that the test suite should finish, with some errors.
